### ISSUE TITLE
cannot clone the book's repository

### ISSUE THREAD

**Issue by mohsenSy** [0xhiro/thebook#1]
I just downloaded this CLI tool and tried to run it with this command
```
thebook
```

I'm getting this error output
```
book does not exist
Cloning the book from: https://github.com/rust-lang/book
thread 'main' panicked at 'failed to clone: authentication required but no callback set; class=Ssh (23); code=Auth (-16)', /home/mouhsenibrahim/.cargo/registry/src/github.com-1ecc6299db9ec823/thebook-0.1.1/src/main.rs:72:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like a bug in `git2` dependency or am I doing something wrong?

Thanks a lot for writing this I just started learning rust 2 weeks ago and really enjoying it

**Comment by 0xhiro** [comment]
Thanks for the feedback. Really appreciate it! What OS are you on? and have you attempted trying it again?

**Comment by mohsenSy** [comment]
I'm running Ubuntu 20.04, `Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`, I tried multiple times without luck, the directory `~/.thebook` is created but it is empty

**Comment by 0xhiro** [comment]
I have implemented a fix. can you please test this by using `cargo install thebook --git https://github.com/0xhiro/thebook.git`

**Comment by mohsenSy** [comment]
thanks it works now :)

**Comment by 0xhiro** [comment]
Awesome! Thanks! Closing as resolved
