### ISSUE TITLE
Visual Studio Code Support

### ISSUE THREAD

**Issue by Nbjohnston86** [0xhiro/thebook#2]
Hello, I saw earlier that you wanted to add it to your to-do list, but I do not know where that is, so I figured I'd add it as an issue, at least.

I only bring this up, because currently when I run `thebook` it looks like it's trying to open in Visual Studio Code on my computer by default, which is admittedly something I probably did to my environment to make that happen.

Is there a workaround I can use so that it does not open it using my default settings until you add support? Thank you.

Environment details:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by 0xhiro** [comment]
Thanks for the issue. Running `thebook` only does the job of opening 'The Book' in your default web browser. So whatever browser is default on your computer will open a local offline copy of 'https://doc.rust-lang.org/book/'. I'm surprised it's VS code that gets opened. Is it by any chance your default browser? if that's possible.

**Comment by Nbjohnston86** [comment]
Interestingly enough, it is not. How very peculiar.
![image](https://user-images.githubusercontent.com/4921306/204545746-aaa1ad60-40ff-4759-bd8f-ffd2481c0df0.png)

When I try searching, it actually works seemingly the way you want it to:
![image](https://user-images.githubusercontent.com/4921306/204546304-58c164b2-0d33-498c-b885-d2e371f5825f.png)

Confusing. Wonder what I did.

**Comment by 0xhiro** [comment]
I will try to look into this. Probably a config issue from your end, but i will try to figure out why this happens. Do let me know if it gets resolved.

**Comment by Nbjohnston86** [comment]
Now that I have time, I decided to do some more digging. I was unsatisfied with what I was finding by default. 

I found more ways to look at default programs, and found some interesting things out.
https://help.ubuntu.com/stable/ubuntu-help/files-open.html.en

I looked at the code you have, and found where the book gets installed. I used the guide listed above, I discovered this:
![image](https://user-images.githubusercontent.com/4921306/204641089-0e251b62-b3dd-442b-9e06-5fbbafac8d60.png)

There's the culprit. Though I became curious as to why? Where was this setting different? I tested a few things more:
`xdg-open https://www.google.com` opens the URL in firefox.
`xdg-open appendix-00.html` failed with message: `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
That was weird. It's supposed to open the file with either firefox or visual studio code, but *it failed*. Oh well, next attempt.

I found, then lost the the website that discusses this, but I found another thing to check: `sudo gedit /usr/share/applications/defaults.list`
`.html` was in there, but it was associated with firefox! So, my right click menu is doing what your application does.
When given the local `.html` file, `xdg-open` fails, though I do not know why.

Out of curiosity, I was wondering if it had something do do with URL vs File paths and ran:
`xdg-open https://doc.rust-lang.org/book/ch01-00-getting-started.html`
This opened in firefox. So ending in `.html` does not matter if it's a URL.

Finally, I found this thread here:
https://askubuntu.com/questions/90214/how-do-i-set-the-default-program

This lead me to look at `~/.config/mimeapps.list` in my text editor and when I looked inside:
`text/html=code-url-handler.desktop` Bingo.

My case ended up being an esoteric one, but it seems as though your webbrowser function that you call... doesn't actually open your default browser. It seems as though it opens the default application for that file type instead, which in my case was visual studio code. So this is actually not a bug with your code, but with webbrowser's, a dependency you use. How fun!

So now you have an error you can submit to them.
I have decided not to fix this for now, in case I find their bug reporting mechanism, so I can show it off. But the bug part of this is done. Now you just have the feature request part. Have fun!

**Comment by 0xhiro** [comment]
That was some detective work. Well done! I will make an issue on the repo. Thanks for the discovery.

**Comment by 0xhiro** [comment]
This issue is being worked on and should be fixed in the next release. In terms of VS Code support, can you go into more details about how you would like it to be?

**Comment by 0xhiro** [comment]
This issue has been fixed in the latest release.
