### ISSUE TITLE
openssl (libssl-dev) dependancy.

### ISSUE THREAD

**Issue by sfarq** [0xhiro/thebook#3]
Hi,
Just a note to say that when installing, i got the following error:
error: failed to run custom build command for `openssl-sys v0.9.78`
Caused by:
  process didn't exit successfully: `/tmp/cargo-installJrrJtj/release/build/openssl-sys-689f17fcd246adcc/build-script-main` (exit status: 101)

It does helpfully tell you that you need to install libssl-dev for the openssl-sys crate to compile. 
You might want to let people know that this is a dependency when installing.

Everything else looks perfect! Thanks for creating it!

FYI Running Debian11 stable.

**Comment by 0xhiro** [comment]
Thanks for the heads up! I intend to reduce the number of dependencies anyways. `openssl-sys` seems to be a dependency of a dependency 'git2', which i recently removed entirely. I will add a section on the readme to specify dependencies used such as 'mdbook' etc.

**Comment by 0xhiro** [comment]
A new version has been published which should fix this. Can you run `cargo install thebook` to update to the latest, and see if it fixes it?

**Comment by 0xhiro** [comment]
Thanks for the help! Arigato!
