### ISSUE TITLE
Consider changing the keys to commonly used alternatives

### ISSUE THREAD

**Issue by David-Else** [0xhiro/thebook#4]
Thanks for this awesome app!

I think it would be better to use Vim keys `l` and `h` as well as the arrows for moving backwards and forwards? `a` and `d` have no meaning I know of, are they from another commonly used app?

If it were up to me it would be `q` for quit, but that is only because it is the default in `mpv`...  but I am still not sure why `c` would be better?

**Comment by 0xhiro** [comment]
A and D comes from gaming LMAO. I am a game developer so my intuition told me to use A and D, but thinking it through, i should have used L and H. I think it won't hurt to have them all, including both C and Q for quiting? C stands for Close btw. Thanks for the feedback, i really appreciate it!

**Comment by 0xhiro** [comment]
The keys have been added.

**Comment by David-Else** [comment]
I just tried it, thanks for the update, but there is no `j` and `k` for down and up, I assumed these would get added, the arrows are still needed to scroll up and down the documents so it is not quite Vim key compatible yet.

**Comment by 0xhiro** [comment]
It is now vim-compatible. Please update to the latest version. Thanks!

**Comment by David-Else** [comment]
I am guessing you are not a vim user :) `j` is down and `k` is up, afraid they are the wrong way around in the new version.

**Comment by marcelarie** [comment]
Yes the `j` and `k` keys are inverted, and it would be amazing to have `gg` and `G` to go to the top and bottom of the file respectably. Maybe is too much to ask. Would a PR with those changes be welcome @0xhiro ??

**Comment by 0xhiro** [comment]
Already working on this. Thanks for the heads-up 🤧

**Comment by 0xhiro** [comment]
Fixed the key inverted keys. If there are more vim bindings, you can send a PR thanks!
