### ISSUE TITLE
`class="caption"` text not being rendered properly

### ISSUE THREAD

**Issue by David-Else** [0xhiro/thebook#5]
Rather than rendering in any style, captions are being displayed as HTML as follows:
```
<span class="caption">Listing 10-25: A function we defined in Listing 4-9 that            ▐
compiled without lifetime annotations, even though the parameter and return               ▐
type are references</span>
```
For example on the `Lifetime Elision` page.

**Comment by 0xhiro** [comment]
Thanks! This is a known issue. The markdown files for "The Book" contain lots of HTML tags, which are not bad, but the markdown parser i use does not support them especially <span> tags "yet". I am working on making this possible along with syntax highlighting for the code rendered. I will update you on the progress. making this a milestone

**Comment by David-Else** [comment]
Cool! Do you know how you going to do the syntax highlighting? For open source Rust code you could use the Helix treesitter code and themes, or the Bat highlighting code and themes https://github.com/sharkdp/bat

**Comment by 0xhiro** [comment]
As much as i know, the markdown renderer i use is currently not working on syntax highlighting. Unless i'll be using a different one, then this is currently unplanned. Check out this issue https://github.com/Canop/termimad/issues/1

**Comment by 0xhiro** [comment]
For the HTML tags, i will work on removing all HTML tags since they are not needed in this context.

**Comment by 0xhiro** [comment]
The `class="caption"` issue has been fixed in the latest release. Thanks for the report!
