### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sfarq** [0xhiro/thebook#6]
Hello,
Enjoying the tool (i am a rust novice so finding quite useful - thanks again). I have a couple of suggestions, not sure if you have these on your list of things to do anyway...

- o for opening the actual Book, this should take you to the page you opened it from, rather than the beginning of the book. 
- Refreshing the downloaded book. There should be a command line argument for re-downloading TheBook, or automatically refreshing it opening. Maybe some sort of monthly prompt to ask the user if they want to refresh it?
- Find/Highlight words. It would be good to be able to do a basic search for words within an open page. i.e VIM keyboard short cut '/' and type words to search on the page. ('n' for next and 'N' for previous - again VIM standard)
- Page linking. Appreciate this is probably a bit more effort, but it would be really cool to navigate around the book, (inside the results), using the book links provided...

Also - how do you feel about pull requests? would you be open to include them if we  submitted fixes / features?

**Comment by 0xhiro** [comment]
I would love to have these features added. Pull requests are very welcome!

**Comment by 0xhiro** [comment]
I'm already working on the first and second features stated above though.

**Comment by marcelarie** [comment]
quick fix list for the word searches would be amazing :)

**Comment by 0xhiro** [comment]
> quick fix list for the word searches would be amazing :)

Can you please elaborate on this?

**Comment by marcelarie** [comment]
> Can you please elaborate on this?
Yes, if you implement a search by paterns, for example by a string, you could implement a list of all the matches and commands/keybinds to iterate on the results.

That is basically a quick fix list, if you use the same mechanics that vim uses it will be easier for a lot of users that already use that functionality.

**Comment by 0xhiro** [comment]
# New features added

> Hello, Enjoying the tool (i am a rust novice so finding quite useful - thanks again). I have a couple of suggestions, not sure if you have these on your list of things to do anyway...
> 
>     * o for opening the actual Book, this should take you to the page you opened it from, rather than the beginning of the book.
> 

1. When you hit O while in the terminal, the browser now opens in the current page you are reading


 
>     * Refreshing the downloaded book. There should be a command line argument for re-downloading TheBook, or automatically refreshing it opening. Maybe some sort of monthly prompt to ask the user if they want to refresh it?
> 

2.  You can now reset the downloaded book and get a fresh copy by running `thebook --reset`


Other features are still pending, pull requests are very welcome

**Comment by 0xhiro** [comment]
@sfarq @marcelarie I will be closing this particular issue. Please open new separate issues for the yet to be implemented features, in order to track changes easily. Thanks.
